version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - sql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3
    # networks:
    #   - app-tier
  
  django:
    build:
      context: ./backend
    container_name: django
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend/:/backend/
      - sql-db:/var/lib/mysql
    depends_on:
      - mysqldb
      - graphite
    # networks:
    #   - app-tier
    restart: always
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    # networks:
    #   - app-tier
    restart: always

  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
    environment:
      - GRAPHITE_STORAGE_DIR=/var/lib/graphite/storage
      - GRAPHITE_CONF_DIR=/var/lib/graphite/conf
      - GRAPHITE_LISTEN=:80
      - GRAPHITE_ADMIN_EMAIL=admin@example.com
      - GRAPHITE_ADMIN_PASSWORD=admin
    volumes:
      - graphite-data:/var/lib/graphite
      - ./graphite:/var/lib/graphite/conf

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root
    # networks:
    #   - app-tier
    restart: always
    depends_on:
      - graphite

volumes:
  sql-db:
  grafana-data:
  graphite-data:

# networks:
#   app-tier:
#     driver: bridge
