version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - django
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"